
sudo: required

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE

# whitelist

before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh

install:
  - .travis/travis_install.sh

#run unit tests here
script: ls
